### ISSUE TITLE
FST_ERR_PROMISE_NOT_FULLFILLED

### ISSUE THREAD

**Issue by LarryEitel** [reactive-web/reactive-cms#174]
Hello, I am very intrigued with your project. I am exploring your fastify stack. 

I and running docker on windows with all containers lit up. I am having to reacquaint myself with Docker.
$ d ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                      NAMES
35320503349c        rcms-nginx-img:latest     "/bin/sh -c 'cp ./ng…"   11 hours ago        Up 11 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   rcms-nginx-service
baab5a2ebf21        rcms-nodejs-img:latest    "npm run server-deve…"   11 hours ago        Up 11 hours                                                    rcms-app-service
9892aa386a90        rcms-mongodb-img:latest   "mongod --bind_ip_all"   11 hours ago        Up 11 hours         0.0.0.0:27017-27018->27017-27018/tcp       rcms-mongodb-service
6eb903818443        rcms-nodejs-img:latest    "npm run dashboard-d…"   11 hours ago        Up 11 hours                                                    rcms-dashboard-app

docker logs baab5a2ebf21 -f --tail 100

I can get to web form however when I submit, I get in log:

0|REACTIVE-CMS  | {"level":30,"time":1603459171118,"pid":35,"hostname":"rcms-app-service","reqId":70,"req":{"method":"POST","url":"/setup","hostname":"localhost","remoteAddress":"192.168.3.4","remotePort":55898},"msg":"incoming request","v":1}
0|REACTIVE-CMS  | {"level":40,"time":1603459171129,"pid":35,"hostname":"rcms-app-service","reqId":70,"msg":"viewsSaved is not iterable","stack":"TypeError: viewsSaved is not iterable\n    at Object.exports.websiteSetupSetInitialConfig (/reactive-cms/server-app/module/website/controller.js:89:22)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","v":1}
0|REACTIVE-CMS  | {"level":30,"time":1603459171134,"pid":35,"hostname":"rcms-app-service","reqId":70,"res":{"statusCode":500},"responseTime":15.217699997127056,"msg":"request completed","v":1}
0|REACTIVE-CMS  | {"level":30,"time":1603459171347,"pid":35,"hostname":"rcms-app-service","reqId":71,"req":{"method":"GET","url":"/favicon.ico","hostname":"localhost","remoteAddress":"192.168.3.4","remotePort":55900},"msg":"incoming request","v":1}
0|REACTIVE-CMS  | {"level":30,"time":1603459171348,"pid":35,"hostname":"rcms-app-service","reqId":71,"res":{"statusCode":302},"responseTime":0.49560000002384186,"msg":"request completed","v":1}
0|REACTIVE-CMS  | {"level":30,"time":1603459171353,"pid":35,"hostname":"rcms-app-service","reqId":72,"req":{"method":"GET","url":"/setup","hostname":"localhost","remoteAddress":"192.168.3.4","remotePort":55902},"msg":"incoming request","v":1}
0|REACTIVE-CMS  | {"level":50,"time":1603459171355,"pid":35,"hostname":"rcms-app-service","reqId":72,"err":{"type":"FastifyError","message":"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]: FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /reactive-cms/node_modules/fastify/lib/wrapThenable.js:34:30\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","name":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","v":1}
0|REACTIVE-CMS  | {"level":30,"time":1603459171359,"pid":35,"hostname":"rcms-app-service","reqId":72,"res":{"statusCode":200},"responseTime":5.610799998044968,"msg":"request completed","v":1}

Are you still actively working on this project? Is it running somewhere that I can see?

Thank You

**Comment by eduardobc88** [comment]
Hi, sorry. Yes let me check this.
